spring:
  application:
    name: library
  datasource:
    url: jdbc:postgresql://${DB_HOST}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASS}
  liquibase:
    change-log: classpath:db/changelog/changelog-root.xml
  jpa:
    open-in-view: true

server:
  servlet:
    context-path: /api

springdoc:
  swagger-ui:
    path: /api-docs

borrow:
  limit: ${BORROW_LIMIT}
